tianocore/edk2-basetools

edk2basetools/Ecc/Check.py

The Ecc tool checks the format of the include guard. This check is
currently done on all the names following the '#ifndef' statement.
It should only be done on the first include guard.
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3252
Reviewed-by: Liming Gao <liming.gao@intel.com>

BaseTools/Ecc: Make Ecc only check first include guard

---

edk2basetools/AutoGen/GenMake.py

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3653
Use the value set in tools_def.txt when the makefile type is
not explicitly set via BuildOption. This allows to have a
valid default makefile name instead of an empty string.
Also use GMAKE_FILETYPE instead of hard-coded "gmake".
Reviewed-by: Chris Jones <christopher.jones@arm.com>

BaseTools/GenMake: Use ToolDefinition as fallback option

---

edk2basetools/build/build.py

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3653
Running the following command:
python3 build/build.py -a AARCH64 -t GCC5
-p ArmPlatformPkg/ArmPlatformPkg.dsc -b DEBUG libraries
triggers the following error:
make: *** Build/ArmPlatform/DEBUG_GCC5/AARCH64/MdePkg/Library/
BasePcdLibNull/BasePcdLibNull: Is a directory.  Stop.
Indeed, MakefileName is set to en empty string. Setting MakefileName
resolves the error.
Reviewed-by: Chris Jones <christopher.jones@arm.com>

BaseTools/build: Set MakefileName

---

edk2basetools/AutoGen/ModuleAutoGen.py
edk2basetools/Workspace/BuildClassObject.py
edk2basetools/build/build.py

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3653
The Makefile and MakefilName fields are never set/used. Remove them.
To check this, the following commands can be used:
- grep -rIn "\.Makefile"
- grep -rIn "\.MakefileName"
Reviewed-by: Chris Jones <christopher.jones@arm.com>

BaseTools: Remove Makefile/MakefileName fields

---

edk2basetools/GenFds/GenFds.py
edk2basetools/GenFds/GenFdsGlobalVariable.py
edk2basetools/TargetTool/TargetTool.py
edk2basetools/Workspace/DscBuildData.py
edk2basetools/build/build.py

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3653
The "target.txt" and "tools_def.txt" filenames are hard-coded
at some places when global definitions are available at:
BaseTools/Source/Python/Common/TargetTxtClassObject.py:
DefaultTargetTxtFile
and
BaseTools/Source/Python/Common/ToolDefClassObject.py:
DefaultToolsDefFile
Use these global definitions instead.
Also remove the unused gBuildConfiguration and gToolsDefinition
variables from build.py
Reviewed-by: Chris Jones <christopher.jones@arm.com>

BaseTools: Remove hard-coded strings for target and tools_def

---

edk2basetools/Ecc/EccMain.py
edk2basetools/GenFds/FfsInfStatement.py
edk2basetools/GenFds/GenFds.py

Currently the realpath is used when parse modules, which shows the
path with a drive letter in build log. In Windows 'subst' comand is
used to associates a path with a drive letter, when use the mapped
drive letter for build, with realpath function the build log will
have different disk letter info which will cause confusion. In this
situation, if use adspath function to show the path info, it will keep
same letter with the mapped drive letter, which avoids confusion.
This patch modifies the realpath to abspath.
Signed-off-by: Yuwei Chen <yuwei.chen@intel.com>
Reviewed-by: Bob Feng <bob.c.feng@Intel.com>

BaseTools: Change RealPath to AbsPath

---

edk2basetools/AutoGen/AutoGenWorker.py
edk2basetools/AutoGen/DataPipe.py
edk2basetools/AutoGen/GenVar.py

SHA-1: 266ae79854ea44ec9b03ff4c9e8e4e7ba2f09fbd
BaseTools: Fix the bug of --cmd-len build option
currently the --cmd-len build option does not work.
This patch is going to fix this bug.
SHA-1: df66bccf6486bb19a48f0582f7d7ad1643841342
* BaseTools: Fix wrong variable header size
There are two type variable header and their size are different,
need to use matched size when calculating offset info, otherwise
it'll destroy other variables content when patching.

Fix wrong variable header size and Fix the bug of --cmd-len build option

---

edk2basetools/Workspace/DscBuildData.py

For the multiple SKU case, basetools generates multiple redundant
__FLEXIBLE_SIZE statement that is from the same line in dsc file.
This behavior causes the generated PcdValueInit.c file to have huge size,
and the compilation time is very long.
This patch is going to fix this issue.
Signed-off-by: Bob Feng <bob.c.feng@intel.com>
Cc: Yuwei Chen <yuwei.chen@intel.com>
Reviewed-by: Yuwei Chen <yuwei.chen@intel.com>

BaseTools: Remove the redundant __FLEXIBLE_SIZE from PcdValueInit.c

---

edk2basetools/AutoGen/AutoGenWorker.py
edk2basetools/AutoGen/DataPipe.py
edk2basetools/Workspace/DscBuildData.py
edk2basetools/Workspace/InfBuildData.py
edk2basetools/Workspace/WorkspaceCommon.py

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3828
This is a bugfix of
bf9230a9f3dde065c3c8b4175ccd32e44e8f0362.
1.In the current code, gPlatformFinalPcd will save all PCDs used at
whole compile process, which wastes runtime memory and is unnecessary.
This patch makes gPlatformFinalPcd save only the PCDes which are
assigned in the DSC file, and the PCD that has not been assigned will
use the default value in DEC.
2.During the compilation process, gPlatformFinalPcd may be lost, and
the current code cannot selectively assign PCD in DSC by specifying ARCH.
This patch moves gPlatformFinalPcd into datapipe and modifies the
assignment logicto fix this.
Signed-off-by: yi1 li <yi1.li@intel.com>
Reviewed-by: Bob …

BaseTools: Move gPlatformFinalPcd to Datapipe and optimize size

---

edk2basetools/AutoGen/BuildEngine.py
edk2basetools/AutoGen/GenMake.py
edk2basetools/AutoGen/ModuleAutoGen.py
edk2basetools/UPT/Library/DataType.py

RVCT is obsolete and no longer used.
Remove support for it.
Signed-off-by: Rebecca Cran <quic_rcran@quicinc.com>
Reviewed-by: Ard Biesheuvel <ardb@kernel.org>

BaseTools: Remove RVCT support

---

edk2basetools/Workspace/DscBuildData.py

The generated Makefile was missing a dependency.  This resulted in a
build-time race condition if the recursive make is multi-threaded and
shares job control.
Signed-off-by: Jake Garver <jake@nvidia.com>

BaseTools: Fix dependency issue in PcdValueInit

---

edk2basetools/AutoGen/GenMake.py
edk2basetools/Workspace/DscBuildData.py

Currently BaseTools use 'cp' command for PcdValueInit and GenMake
process, as the command can not keep the time info of the source
file, which will cause incremental build issue in Linux system,
thus the '-p' need be added to keep the source file's attributes
in copy process.
This patch fixes this issue.
Signed-off-by: Yuwei Chen <yuwei.chen@intel.com>

BaseTools: add '-p' for Linux 'cp' command.

---

edk2basetools/Workspace/DscBuildData.py

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3965
Currently DSC LibraryClass precedence rule is not align with DSC Spec.
The expectation rule should be:
[LibraryClasses.$(ARCH)] < [LibraryClasses.Common.$(MODULE_TYPE)]
The actual behavior is:
[LibraryClasses.$(ARCH)] > [LibraryClasses.Common.$(MODULE_TYPE)]
This patch fixes the issue.
Cc: Long1 Huang <long1.huang@intel.com>
Cc: Ray Ni <ray.ni@intel.com>
Signed-off-by: Yuwei Chen <yuwei.chen@intel.com>

BaseTools: Fix DSC LibraryClass precedence rule

---

edk2basetools/Workspace/InfBuildData.py

This patch is a bug fix about FeatureFlagExpression in INF file:
INF [Source] section now unconditionally use Pcd default value in DEC
when handling FeatureFlagExpression, it is wrong.
If a Pcd value has been set in the DSC file, we should use latest
value in DSC instead of default value.
Signed-off-by: Yi Li <yi1.li@intel.com>

BaseTools: INF should use latest Pcd value instead of default value

---

edk2basetools/Common/VpdInfoFile.py

Popen communication returns bytestrings. It is necessary to perform decode on these strings before passing them to the EdkLogger that works with ordinary strings.

BaseTools: Correct BPDG tool error prints

---

edk2basetools/Ecc/EccToolError.py
edk2basetools/build/build.py

In an effort to clean the documentation of the above package, remove duplicated words.
Signed-off-by: Pierre Gondois <pierre.gondois@arm.com>

BaseTools: Remove duplicated words in Python tools

---

edk2basetools/FMMT/FMMT.py
edk2basetools/FMMT/core/FMMTOperation.py
edk2basetools/FMMT/core/FvHandler.py

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3938
This function is used to remove the useless FV free space. Usage: FMMT -s Inputfile Outputfile
Signed-off-by: Yuwei Chen <yuwei.chen@intel.com>

BaseTools/FMMT: Add Shrink Fv function

---

edk2basetools/CommonDataClass/FdfClass.py
edk2basetools/GenFds/FdfParser.py
edk2basetools/GenFds/SubTypeGuidSection.py

EFI_SECTION_FREEFORM_SUBTYPE_GUID is a leaf section type that contains a single EFI_GUID in the header to describe the raw data. Currently is is not possible to generate such section. This patch adds initial support for the generation of such sections. The added syntax for this type of section corresponds to EDKII "[FV] section" documentation from the FDF Specification:
```
SECTION SUBTYPE_GUID <GUID> = <File>
```

BaseTools: Add support for SUBTYPE_GUID section generation

---

edk2basetools/GenFds/FdfParser.py

Corrently the set of file types for the PIC section contains two duplicate values.
Replace the duplicate value with the correct one to fix the issue.

BaseTools/GenFds: Correct file type set for the PIC section

---

edk2basetools/Workspace/DscBuildData.py

Currently it is not possible to initialize all elements in the array PCD.
For example, this PCD would result to a build failure: gTokenSpaceGuid.PcdArray|{0x11, 0x22}|UINT8[2]|0x4C4CB9A3
Correct logical operator in the initialization data size checks to fix the issue.

BaseTools: Correct initialization data size check for array PCDs

---

edk2basetools/Common/Expression.py

Currently the PCD values calculated from the expressions have different formating from the simple byte arrays in AutoGenC.
Example:
The following definition in DEC:
gTokenSpaceGuid.PcdArray|{0x44, 0x33, 0x22, 0x11}|VOID*|0x55555555 gTokenSpaceGuid.PcdArrayByExpression|{UINT32(0x11223344)}|VOID*|0x66666666
Produces these strings in AutoGenC:
<...> _gPcd_<...>_PcdArray[4] = {0x44, 0x33, 0x22, 0x11}; <...> _gPcd_<...>_PcdArrayByExpression[4] = {0x44,0x33,0x22,0x11};
Add missing space character between the array elements to unify PCD value formatting.

BaseTools: Add missing spaces for PCD expression values in AutoGenC

---

edk2basetools/GenFds/SubTypeGuidSection.py
edk2basetools/build/BuildReport.py
edk2basetools/build/buildoptions.py

REF:https://bugzilla.tianocore.org/show_bug.cgi?id=2850
Add "-Y REPORT_INFO" option to build command to generate compile information as part of BuildReport.
This option generates files to be used by external tools as IDE's to enhance functionality.
Files are created inside build folder:
<Build>/<BuildTarget>/<ToolChain>/CompileInfo
Files created:
* compile_commands.json - Compilation Database. To be used by IDE's to enable advance features
* cscope.files - List of files used in compilation. Used by Cscope to parse C code and provide browse functionality.
* module_report.json - Module data form buildReport in Json format.

BaseTools: Generate compile information in build report

---

edk2basetools/Workspace/DscBuildData.py

CC_FLAGS2 also needs to be set when running on Windows, otherwise the wrong line is added and nmake fails when building using Visual Studio.

DscBuildData.py: set CC_FLAGS2 when running on Windows

---

setup.py

The project no longer uses lists.01.org. Since bugs@edk2.groups.io is an automated list that few likely monitor for messages, set the email address to devel@edk2.groups.io.
Issue: #91

Fix the author email in setup.py

---

edk2basetools/UPT/Core/FileHook.py

As of Python 3.3, os.rmdir takes an optional parameter dir_fd. Add it to _hookrmdir to avoid the following error when running pytest:
>   os.rmdir(path, dir_fd=dir_fd)
E   TypeError: _hookrmdir() got an unexpected keyword argument 'dir_fd'

UPT/Core/FileHook.py: Add the dir_fd parameter to _hookrmdir

---

edk2basetools/Workspace/DscBuildData.py

Since everyone should now be running a version of edk2 that expects CFLAGS instead of BUILD_CFLAGS, remove the compatibility code.

Remove the BUILD_CFLAGS compatibility code in Workspace/DscBuildData.py

---

edk2basetools/FMMT/core/FvHandler.py

In FMMT replace function, when newffs size <= targetffs size, the new free space is calculated wrong as loss the pad data delta size. That will cause invalid binary generated.
This patch fixes this issue.
Cc: Rebecca Cran <rebecca@bsdio.com>

BaseTools: FMMT replace new free space fixing in replace

---

requirements.publisher.txt

The build package is now required to publish packages.

Add build package to requirements.publisher.txt

---

pyproject.toml

Specify the py-modules to be just edk2basetools since the CI process leaves folders around which confuses the build.

Specify py-modules since CI leaves folders around confusing build

---

pyproject.toml

PyPI only accepts "BSD License" and doesn't have any knowledge of the BSD + Patent license. So fix the classifier to just be "BSD License".

Fix license classifier: 'BSD+Patent' isn't valid for PyPI

---

edk2basetools/AutoGen/GenC.py

https://bugzilla.tianocore.org/show_bug.cgi?id=991
~~~
Most module types have standardized entry point function prototypes. They
are declared in headers like
- MdePkg/Include/Library/PeiCoreEntryPoint.h
- MdePkg/Include/Library/PeimEntryPoint.h
- MdePkg/Include/Library/DxeCoreEntryPoint.h
- MdePkg/Include/Library/UefiDriverEntryPoint.h
- MdePkg/Include/Library/UefiApplicationEntryPoint.h
These header files also declare matching ProcessLibraryConstructorList()
prototypes.
The SEC module type does not have a standardized entry point prototype
(aka parameter list), therefore no header file like the above ones exists
for SEC. Consequently, no header file *declares*
ProcessLibraryConstructorList() for SEC modules, even though AutoGen
always *defines* ProcessLibraryConstructorList() with the …

BaseTools/AutoGen: declare ProcessLibraryConstructorList() for SEC modules

---

edk2basetools/FMMT/core/GuidTools.py

When the FMMTConf.ini file has empty lines then it used to throw errors GuidTool load error!, this patch is to skip checking for empty lines in the ini file

FMMT Skip empty Lines while parsing FMMTConfig.ini

---

edk2basetools/build/BuildReport.py

Add source file to the `command`. The compilation database format requires including the source file name in the `command`, since the `command` must be the full command used to compile. When the source file is absent, it can break tools that use the compilation database, such as SonarQube.

Fix compilation database generator

---

pyproject.toml

Fix pyproject.toml: the py-modules line doesn't cause the package to include the edk2basetools module. Switching it to packages fixes this.
Fixes issue #124

Fix [tools.setuptools] in pyproject.toml
